# Constantes de calcul
PONDERATION_CC = 0.4
PONDERATION_EXAMEN = 0.6
PENALITE_PAR_HEURE = 0.01
SEUIL_REUSSITE = 10.0
CREDITS_SEMESTRE = 30

# Seuils des Mentions
MENTION_PASSABLE = 10.0
MENTION_ASSEZ_BIEN = 12.0
MENTION_BIEN = 14.0
MENTION_TRES_BIEN = 16.0
