@startuml ComponentDiagram
skinparam componentStyle uml2

package "PWA / Client Side (Nuxt 3)" {
  [Premium UI (Monochrome)] as UI
  [PWA Service Worker] as PWA
  [Store Pinia / Cache] as Store
  [Moteur jsPDF (Client)] as jsPDF
  [Aura Engine (Canvas)] as Aura
}

package "Backend Django DDD (Render)" {
  folder "Interfaces" {
    [API Controllers] as API
    [JWT Validator] as AuthMid
  }
  
  folder "Application" {
    [Services Applicatifs] as Svc
    [Audit & Logs] as Audit
  }
  
  folder "Domaine" {
    [Orchestre Calcul (DDD)] as Calc
    [Entités Métier] as Domain
  }
  
  folder "Infrastructure" {
    [Django ORM Repositories] as Repo
    [Supabase Adapter] as AuthSvc
  }
}

database "PostgreSQL (Supabase)" as DB
cloud "Supabase Cloud Auth" as SupaAuth

PWA --> UI
UI --> Aura
UI --> jsPDF
UI --> Store
Store --> API
API --> AuthMid
AuthMid --> AuthSvc
API --> Svc
Svc --> Audit
Svc --> Calc
Calc --> Domain
Svc --> Repo
Repo --> DB
AuthSvc --> SupaAuth
@enduml
