@startuml SequenceBulletin
skinparam participantPadding 20

actor "Secrétariat" as S
participant "Backend API" as B
participant "BulletinService" as SVC
participant "ResultatRepository" as REP
participant "PDFGenerator (WeasyPrint)" as GEN

S -> B : GET /api/bulletins/{etudiantId}
B -> SVC : genererBulletin(etudiantId)
SVC -> REP : getResultatsComplets(id)
REP -->> SVC : Data (JSON/Entity)

SVC -> SVC : Formater Template HTML
SVC -> GEN : convertHTMLToPDF(html)
GEN -->> SVC : ByteStream (PDF)

SVC -->> B : Fichier PDF
B -->> S : Flux de téléchargement (Binary)
@enduml
