version: '3.8'

services:
  backend:
    build: .
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - firebase-emulator
    networks:
      - bull-network

  firebase-emulator:
    image: spinejs/firebase-emulator:latest
    ports:
      - "9099:9099" # Auth
      - "8080:8080" # Firestore
      - "4000:4000" # UI
    networks:
      - bull-network
    volumes:
      - ./firebase_data:/app/data

networks:
  bull-network:
    driver: bridge