services:
  - type: web
    name: bulletin-backend
    runtime: python
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DJANGO_DEBUG
        value: "False"
      - fromGroup: bulletin-secrets # Groupe de secrets à créer sur Render
