# Generated by Django 5.2.3 on 2026-04-21 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultatAnnuelModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.CharField(max_length=20)),
                ('valeur_moyenne', models.FloatField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_annuels', to='django_models.etudiantmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultatSemestreModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_semestre', models.IntegerField()),
                ('valeur_moyenne', models.FloatField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_semestre', to='django_models.etudiantmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultatUEModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur_moyenne', models.FloatField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats_ue', to='django_models.etudiantmodel')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='django_models.uemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
