# Generated by Django 5.2.3 on 2026-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0002_resultatannuelmodel_resultatsemestremodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignantmodel',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enseignantmodel',
            name='specialite',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
