# Generated by Django 5.2.3 on 2026-04-27 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0003_enseignantmodel_numero_telephone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinataire_uid', models.CharField(max_length=128)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(default='INFO', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
