# Generated by Django 5.2.3 on 2026-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0004_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uemodel',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
