# Generated by Django 5.2.3 on 2026-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_models', '0005_alter_uemodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestremodel',
            name='libelle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uemodel',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
