@startuml sequence_authentification
actor Utilisateur
participant "Client (Front)" as Front
participant "Firebase Auth" as FB
participant "Backend Django" as API
participant "Firestore" as DB

Utilisateur -> Front: Saisir identifiants
activate Front
Front -> FB: Login (email, pass)
activate FB
FB --> Front: ID Token (JWT)
deactivate FB
Front -> API: Requete (Authorization: Bearer JWT)
activate API
API -> API: Verifier signature JWT
API -> API: Extraire roles (Claims)
API -> DB: Charger profil utilisateur
activate DB
DB --> API: Donnees (Roles, Matieres)
deactivate DB
API --> Front: 200 OK (Donnees demandees)
deactivate API
@enduml
