@startuml state_ue
[*] --> EN_COURS
EN_COURS --> SAISIE_TERMINEE : Notes completes
SAISIE_TERMINEE --> VALIDEE : Moyenne >= 10.0
SAISIE_TERMINEE --> EN_ATTENTE_COMPENSATION : Moyenne < 10.0
EN_ATTENTE_COMPENSATION --> COMPENSEE : Moyenne Generale >= 10.0
EN_ATTENTE_COMPENSATION --> AJOURNEE : Moyenne Generale < 10.0
AJOURNEE --> EN_COURS : Rattrapage ouvert
VALIDEE --> [*]
COMPENSEE --> [*]
@enduml
