@startuml use_case_global
left to right direction
actor "Administrateur" as Admin
actor "Enseignant" as Enseignant
actor "Etudiant" as Etudiant
actor "Secretariat" as Secretariat

rectangle "Systeme de Gestion des Bulletins" {
    usecase "Saisir Notes" as UC1
    usecase "Consulter Resultats" as UC2
    usecase "Generer Bulletins PDF" as UC3
    usecase "Importer Donnees Excel" as UC4
    usecase "Gerer Referentiel (UE/Matiere)" as UC5
    usecase "Consulter Audit Logs" as UC6
    usecase "Valider Semestre (Jury)" as UC7
}

Enseignant --> UC1
Enseignant --> UC2
Etudiant --> UC2
Secretariat --> UC3
Secretariat --> UC4
Secretariat --> UC2
Admin --> UC1
Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5
Admin --> UC6
Admin --> UC7

@enduml
