@startuml use_case_detail_generation_bulletins
left to right direction
actor "Secretariat" as Sec

rectangle "Generation des Bulletins" {
    usecase "Consulter resultats individuels" as UC1
    usecase "Valider compensation (UE)" as UC2
    usecase "Verifier decision Jury" as UC3
    usecase "Generer PDF Bulletin" as UC4
    usecase "Export groupe promotion" as UC5
}

Sec --> UC1
Sec --> UC4
Sec --> UC5
UC4 ..> UC2 : <<include>>
UC4 ..> UC3 : <<include>>
@enduml
